### ISSUE TITLE
The `async.ts` is a `retry` in fact

### ISSUE THREAD

**Issue by vanpipy** [piotr-oles/karton#10]
Hi, @piotr-oles ,

The [async.ts file](https://github.com/piotr-oles/karton/blob/main/src/async.ts) includes a `retry` function only. Moving its name to `retry` will be better?

Another is the `karton` should include and output a `sandbox` and a `test driver` only in my thought..., the others should be a private or a hidden APIs.

thanks.

**Comment by piotr-oles** [comment]
Hi @vanpipy 
The async.ts file exports also `wait` function: https://github.com/piotr-oles/karton/blob/main/src/async.ts#L40

I would not agree that the `karton` should export only `sandbox` and `test driver` - other apis are intended to be public, because you can build custom solution on top of them (like I do in the fork-ts-checker-webpack-plugin e2e tests).

**Comment by vanpipy** [comment]
> Hi @vanpipy The async.ts file exports also `wait` function: https://github.com/piotr-oles/karton/blob/main/src/async.ts#L40
> 
> I would not agree that the `karton` should export only `sandbox` and `test driver` - other apis are intended to be public, because you can build custom solution on top of them (like I do in the fork-ts-checker-webpack-plugin e2e tests).

I got your idea about the design of the `karton`. For the custom solution, the current design is better. The `karton` is the thing i wish, hahah...
